### ISSUE TITLE
not able to activate material theme

### ISSUE THREAD

**Issue by Vapster** [equinusocio/material-theme-appbar#57]
![screenshot 1](https://user-images.githubusercontent.com/22271547/33651142-c72a80bc-da8a-11e7-8254-ded8c8bb8b6a.png)

**Comment by equinusocio** [comment]
Matarial Theme for Sublime Text is deprecated and no more under active development.
https://github.com/equinusocio/material-theme#------this-project-is-not-more-under-active-development-since-sublime-text-is-an-obsolete-software-compared-to-other-editors-please-consider-material-theme-for-visual-studio-code--
